source_directories:
  - /mnt/nextcloud_data
  - /mnt/nextcloud_db
  - /mnt/nextcloud_nextcloud

repositories:
  - path: /mnt/borg-repository

one_file_system: true
read_special: true
compression: lz4
archive_name_format: 'backup-{now}'

keep_daily: 7
checks:
 - name: repository
   frequency: 2 weeks
 - name: archives
   frequency: always
 - name: extract
   frequency: 1 month
 - name: data
   frequency: 1 month

mariadb_databases:
  - name: ${MYSQL_DATABASE}
    hostname: db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    tls: false

commands:
  - before: action
    when:
      - create
    run:
      - echo "Starting a backup job."

  - after: action
    when:
      - create
    run:
      - echo "Backup created."
    states:
      - finish

  - after: action
    when:
      - create
      - prune
      - compact
      - check
    run:
      - echo "Error while creating a backup."
    states:
      - fail

  - before: everything
    when:
      - create
    run:
      - echo "Enabling maintenance mode"
      - echo "<?php \$CONFIG = array('maintenance' => true);" > /mnt/nextcloud_nextcloud/config/maintenance.config.php
      - echo "Starting backups."

  - after: everything
    when:
      - create
    run:
      - echo "Backups created."
      - echo "Disabling maintenance mode"
      - rm /mnt/nextcloud_nextcloud/config/maintenance.config.php
